### ISSUE TITLE
Log-Entries during  „Out of heating period“

### ISSUE THREAD

**Issue by eric2905** [rg-engineering/ioBroker.heatingcontrol#108]
Adapter: v0.5.1
js-Controller:3.1.4

Just switched “out of heating period” (heatingcontrol.0.HeatingPeriodActive) to false.
I don’t use actors.
Adapter is logging very often (more than once per second) “(1273) handling actors out of heating period not implemented yet”

Maybe don’t log this, if “using actors” is not active,

![A1EA53D0-41E3-492C-B113-3CC799E21D99](https://user-images.githubusercontent.com/18639287/82723172-24ed9480-9ccd-11ea-928c-454bd553091a.jpeg)
![16BBE262-6FC4-4453-95E4-C13ED0159F3B](https://user-images.githubusercontent.com/18639287/82723173-274fee80-9ccd-11ea-9d71-3e76cd675a9e.jpeg)

**Comment by rg-engineering** [comment]
I can remove the log, but the root cause is still unclear. You should'nt get get so many events from your devices. The log appears when a thermostat device which is configured in the adapter fires an change event and adapter does not handle it when not in heating period. If you enable debug log you should see the source of change events

**Comment by rg-engineering** [comment]
mit 0.5.7 erledigt
