### ISSUE TITLE
CopyPeriods - destination periods more than source periods

### ISSUE THREAD

**Issue by alfiriel** [rg-engineering/ioBroker.heatingcontrol#459]
Installed version: 2.11.1

CopyPeriods Button should delete all destination periods before copying.

RoomXYZ -> Mon -> Periods -> Filled with 3 Periods

RoomXYZ -> Tue -> Periods -> Filled with 5 Periods

If I use button "heatingcontrol.0.Profiles.1.RoomXYZ.Mon.CopyPeriods", than it copies period 1-3 from Monday to Tuesday. Periods 4 - 5 on Tuesday are still available.
I would expect them to be deleted.

Any suggestions about that?

**Comment by rg-engineering** [comment]
Just that i get it right:
* you have a profile for "every day separately"
* this profile has 5 periods
* now you change the number of periods to three in admin
* then you set the three periods for Monday and press "copyPeriods"
* the three periods from Monday are copied to Tuesday

Nevertheless, you still see two unused periods in the object tree on Monday, Tuesday and also for the rest of the week?

**Comment by rg-engineering** [comment]
@alfiriel any further comment on this?

**Comment by alfiriel** [comment]
> @alfiriel any further comment on this?

Sorry for the late reply.
Your example matches well!

Regards

**Comment by rg-engineering** [comment]
![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/8238668/4a66c733-ebe0-49e5-b6c4-a9bbc847d777)

There is now a log to show that you have unused datapoints and there is a button to delete them.

I don't want to delete those data automatically because then you loose it if you just want to try something. I prefer the user can do that...

**Comment by alfiriel** [comment]
Wow, perfekt. Thank You!
